src/api/routes/render.ts, src/lib/Renderer.ts
This PR gives renderscript the ability to detect when the evaluated page url was different from the url that is was provided and returns a 307 redirect with the location of the evaluated page.
Current known limitations:
- there is no way to make renderscript ignore certain queryParams, so if a uniqueID is generated in the search params, the page will redirect for ever
=> feat(detect-js-redirect): return 307 when evaluated page url is different from initial url

package.json, src/lib/Renderer.ts, yarn.lock
This PR adds the capability for renderscript to reject requests that resolve to private IPs.
Currently blocked because library does not exist yet 😄
=> feat(dns-filter): reject requests to private IPs

README.md, src/lib/Renderer.ts
Closes #11 
This PR adds a new environment variable to give more control on which IPs to allow when running the service with `ALLOW_LOCALHOST=true`.
=> fix(allow-ip-prefixes): add environment variable to control which ips to whitelist

README.md, src/api/routes/render.ts, src/lib/Renderer.ts
This PR introduces the ability to forward headers to the page navigation requests.
It adds an environment variable called `HEADERS_TO_FORWARD` which accepts a comma separated list of headers to forward.
There is also special handling of cookies, since browser do not consider `Cookie` as a regular request header.
go on `https://crawler.algolia.com`, login, and get the Cookie header, then run `yarn dev` and
```sh
✗ curl -i -X POST 'http://localhost:3000/render' \
-d 'url=https%3A%2F%2Fcrawler.algolia.com%2Fadmin%2Fuser_configs%2F${CONFIG_ID}%2Fteam' \
-H 'Cookie: ${Cookie}'
```
=> feat(forward-headers): handle forwarding of generic headers and cookie

src/api/helpers/buildUrl.ts, src/api/routes/render.ts
This PR fixes an issue when running with docker where localhost URLs would be detected as redirects because of the translation of `localhost` into `host.docker.internal`.
We now revert this translation before checking if the resolved url of the rendered page was the same as the initial url, and return a location with `localhost` instead of `host.docker.internal` if there was a redirection.
=> fix(consistent-localhost): revert url translation when checking for redirection

src/lib/Renderer.ts
closes #18 
This PR fixes a bug where the hash of a page would be ignored during the check for redirection for one half of the comparison only, which created infinite loops in certain cases.
```
yarn dev
```
The following query
```
curl -i -X POST 'http://localhost:3000/render' -d 'url=https%3A%2F%2Fwww.algolia.com%2Fdoc%2Fguides%2Fsecurity%2Fapi-keys%2F%23quick-overview'
```
should return a 200 instead of a 307.
=> fix(url-hash-redirect): use window.location.href instead of page.url

src/lib/Renderer.ts, src/lib/helpers/injectBaseHref.ts
The "2 step logging" log was also displayed for a single page login
=> fix: move 2-steps logging logs to the right place

public/static/main.webmanifest, public/test-website/blocked-requests.html, src/__tests__/blockedRequests.test.ts, src/__tests__/index.test.ts, src/lib/TasksManager.ts, src/lib/browser/Browser.ts, src/lib/browser/Page.ts, src/lib/tasks/Task.ts, src/lib/types.ts
- Expose more metrics in the API 
Coming from chrome directly
- Add a few missing tests about metrics and requests blocking
- Missing page close (Next PR I'll find a way to test fro memory leak and page opened to be sure we don't forget to close them)
=> feat: expose more metrics

public/index.html, src/api/routes/login.ts, src/lib/tasks/Login.ts
Some JS based login forms require 2-steps (validating username, then password), but have the password field already present in the first step, hidden.
So the current selector (`input[type=password]`) was detecting this field and was trying to perform a 1-step login.
- Ignore the `aria-hidden` password fields.
- Fixed the `renderHTML` type, as HTML checkboxes don't send a boolean but a string value.
=> fix(login): ignore aria-hidden password fields

public/test-website/slow.html, src/__tests__/async.test.ts, src/api/helpers/errors.ts, src/lib/browser/Page.ts, src/lib/browser/constants.ts
- We wrongly throwed on timeout while it was perfectly expected
- Ignore errors if page has timeout. It seems we can receive response (of other network request), after the page has been closed. Seems weird but that's my interpretation. 
- Add a test that ensure we wait for a timeout and has the appropriate content. This missing test could have saved me some trouble.
=> fix: test max wait

package.json, yarn.lock
It seems that we are facing this issue: https://github.com/puppeteer/puppeteer/issues/7867
Let's try to rollback to puppeteer v11
=> fix: rollback to puppeteer 11

package.json, yarn.lock
It seems that we are facing this issue: https://github.com/puppeteer/puppeteer/issues/7867
Let's tag another version with puppeteer v12
=> fix: rollback to puppeteer v12

jest.config.js, package.json, src/__tests__/api.test.ts, src/__tests__/async.test.ts, src/__tests__/blockedRequests.test.ts, src/__tests__/login.real.test.ts, src/__tests__/redirect.test.ts, src/__tests__/tasksManager.test.ts, src/lib/browser/Page.ts, src/lib/tasks/Render.ts
Following #572 Redirection could still be flaky but I did not realised there was a perfect and simple solution.
- Store the initalResponse and reuse it instead of using the final response.
- Bonus: use postRender where it was not yet used
=> fix: simple solution for redirection

Dockerfile, Dockerfile.pw, scripts/build.sh, scripts/push.sh, src/api/helpers/buildUrl.ts, src/api/routes/render.ts, src/index.ts, src/lib/constants.ts
Renderscript image wasn't optimised at all (+ it was segfaulting)
Made a 3 stages dockerfile
- 1st stage: Playwright only chromium
- 2nd stage: Code + npm install dev
- 3rd stage: Only built code
This results in an acceptable **533.49 MB compressed** image.
```sh
./scripts/build.sh
docker run -p 23000:3000 docker.io/algolia/renderscript
```
Bonus: missing buildUrl/revertUrl for localhost testing.
=> fix(docker): improve dockerfile size

.github/workflows/release.yml, .github/workflows/release_docker.yml
Github Actions setup works:
- semantic-release seems to work, removing the dry-run mode
- build docker on the release commit only so we don't need to mess with git during the CI
=> fix(actions): build docker only on release

.dockerignore, .github/workflows/release.yml, Dockerfile, package.json, yarn.lock
- Make release only manual for the moment, docker is taking a huge amount of time to compile because we need multiple platforms and with it's not ideal to release that much for the moment.
- Add a `dry run` option to release 
- Dockerfile: cache dependencies more aggressively by leveraging a 4th layer (yes), copying the package.json and remove version and useless packages. This should improve build time by a lot and size maybe. And help release because when we release we increment the `version` so it was never using the cache.
```sh
yarn docker:build
```
The first build will be slow and next should be instant.
Then if you modify the version in package.json it should still be instant.
=> fix(release): improve process and dockerfile again

src/api/@types/postRender.ts, src/api/routes/healthy.ts, src/helpers/errorReporting.ts, src/lib/TasksManager.ts, src/lib/browser/Page.ts, src/lib/constants.ts, src/lib/helpers/errors.ts, src/lib/tasks/Render.ts
- Catch all `Target Closed`, they happen either if the page has crashed (unlikely) or the page was closed (happen on navigation or service close) so either way it's perfectly expected we don't need to report them.
- Type errors returned in the API
- Log error when service report unhealthy and increase the default unhealthy period.
=> fix: improve errors reporting

src/__tests__/login.test.ts, src/api/@types/postLogin.ts, src/api/routes/login.ts, src/lib/helpers/errors.ts, src/lib/tasks/Login.ts, src/lib/types.ts
- Catch more errors during login
- Implement the same RetryableErrors strategy as the /render
- Split the code readability
=> fix(login): catch more errors

src/lib/tasks/Login.ts
Return cookie for the original URL that started the login and the resolved URL, because login can redirect to multiple domains.
We could output all the cookies but for the moment I'm not confident with that since names are not unique.
=> fix(cookies): output from original url and resolved url

.github/workflows/release.yml, .github/workflows/release_docker.yml, Dockerfile, scripts/build.sh, scripts/test_image.sh
the chrome version (in /ms-playwright/chrome-XXXX) is linked with the playwright version (according to this [comment](https://github.com/microsoft/playwright-python/issues/168#issuecomment-673956499)), but in the package.json it's fixed and with npx in the Dockerfile it's the latest, so there is a mismatch.
We need to be careful when upgrading playwright version.
Some other changes:
- fix github action syntax
- update images in Dockerfile
- add latest tag
- use wait loop to make the test image faster
=> fix(docker): build image locally and on CI

src/helpers/waitForPendingRequests.ts, src/lib/tasks/Login.ts, src/lib/tasks/Render.ts
Similarly to #654, we to noticed that the login feature could fail because we return too soon, while all requests have not finished yet.
This PR adds the exact same manual check (refactored into a dedicated helper)
=> fix(login): manually wait for pending requests

scripts/test_image.sh, src/lib/browser/Browser.ts
The build of the image is failing because I've updated a log it was relying on.
The bad thing is that it is currently failing with a simple: `Error: Process completed with exit code 1.` (c.f. https://github.com/algolia/renderscript/actions/runs/3639334496/jobs/6152011129)
This is because when grep fails, it actually exits 1 by default, before displaying any error message.
Changes:
- Revert the log message
- Fix the grep check using an `if` as described here: https://stackoverflow.com/a/56170435/1326281
- Move the browser check before trying an actual render
How to test:
- `docker build . -t algolia/renderscript`
- `./scripts/test_image.sh latest`
=> fix: test_image.sh

.github/workflows/release_docker.yml, Dockerfile, scripts/build.sh, scripts/test_image.sh
The release [failed](https://github.com/algolia/renderscript/actions/runs/3937825768) this morning because the version of Playwright set in the `Dockerfile` was not aligned with the one in the `package.json`
This also showed that the `test_image.sh` script was buggy, and exiting too early. Indeed, I've learned that `((...))` in bash returns with an exit code of 1 if the expression is zero: https://unix.stackexchange.com/a/597023/161025
```sh
$ ((TEST=1))
$ echo $?
0
$ ((TEST=0))
echo $?
1
```
Lastly, we've been seeing warning messages during the build: The `set-output` command is deprecated and will be disabled soon. This is due to https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/, and it's a good occasion to fix them.
- Fix …
=> fix(build): align playwright version

src/lib/browser/Page.ts
When fixing the Cookies forwarding (#732), I didn't see that they were only set for for the current URL.
So it was working for the root page, but not for other paths of a website.
- Set cookies for the whole domain
---
CRAW-2472
=> fix: set cookies for the whole domain

src/api/routes/render.ts, src/lib/TasksManager.ts, src/lib/browser/Browser.ts, src/lib/browser/Page.ts, src/lib/tasks/Task.ts
DI-1233
We are seeing some pages failing to render with a [`body_serialisation_failed` error](https://github.com/algolia/renderscript/blob/master/src/lib/tasks/Render.ts#L115).
To understand better what happen:
- Report rendering errors
- Track the rendering time
Also:
- Stop reporting handled errors to not flood the reporting, only count them
=> fix: better error reporting

src/lib/browser/Browser.ts, src/lib/browser/Page.ts
Firefox gets `'disconnected'` regularly, when that happen, we call `this.create();` to start another instance. But it turns out that it can throw an error when trying to launch it, which makes the whole process crash:
```
"browserType.launch: Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> /ms-playwright/firefox-1391/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-LKs7fU -juggler-pipe --no-sandbox --disable-setuid-sandbox --no-zygote --disable-gpu --proxy-server='direct://' --proxy-bypass-list=* --disk-cache-dir=/dev/null --media-cache-size=1 --disk-cache-size=1 --disable-extensions --disable-features=Translate --disable-infobars --disable-notifications --disable-translate --no-default-browser-check …
```
=> fix: catch browser crash on start

renovate.json, yarn.lock
Semantic release has failed since the lock file maintenance that happened in https://github.com/algolia/renderscript/pull/814, with the following error:
```
Error: Command failed with exit code 1: npm version 2.2.10 --userconfig /tmp/ff4edfc49c77d65bf4c043c1e0a4bfc3/.npmrc --no-git-tag-version --allow-same-version
at makeError (file:///home/runner/work/renderscript/renderscript/node_modules/execa/lib/error.js:60:11)
at handlePromise (file:///home/runner/work/renderscript/renderscript/node_modules/execa/index.js:124:26)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async default (file:///home/runner/work/renderscript/renderscript/node_modules/@semantic-release/npm/lib/prepare.js:26:3)
at async prepare …
```
=> fix: semantic release

src/lib/browser/Page.ts
`waitForNavigation` is deprecated, and was throwing error for a specific test page.
Using `waitForLoadState` then `waitForResponse` seems to work better.
=> fix: use waitForLoadState instead of waitForNavigation

src/lib/browser/Adblocker.ts
The query to https://raw.githubusercontent.com/badmojr/1Hosts/master/Pro/domains.txt often make the service startup fail.
We restart this service each time it fails, creating multiple request.
This PR separates the browser startup task from the adblocker load. It lets the adblocker fail "silently", and will definitely still run the browser
=> fix: make the service load independent of adblocker

.github/workflows/main.yml, package.json, src/lib/browser/constants.ts, src/lib/tasks/Login.ts, yarn.lock
In this PR:
A little housekeeping and improvements:
- update Playwright to its latest version - will help improve performance and use latest browsers updates
- update Express to its latest minor
- Add a few more flags to the browser's launch to help optimize javascript rendering (search on [this list](https://peter.sh/experiments/chromium-command-line-switches/#disable-backgrounding-occluded-windows) for what they can do) LMK if you prefer in depth explanation on why I think the flags would work.
=> fix: upgrade playwright and deps

src/helpers/errorReporting.ts, src/lib/TasksManager.ts
Adds tags to some errors related to rendering the page. This is to help track issues within Sentry.
=> feat: Add tagging to Sentry

src/lib/helpers/getInput.ts
Ensures login inputs we are trying to get is visible on the page.
This fixes the case for inputs that might have custom classes and styles.
Playwright docs: https://playwright.dev/docs/locators#matching-only-visible-elements
=> fix: ensure the input is a visible element

src/lib/helpers/getInput.ts, src/lib/types.ts
Sometimes two inputs appear on a login page, one being invisible (to cater for crawlers or password managers). This PR adds the ability to wait for the page to be fully loaded before selecting the right input.
=> fix: account for invisible password input fields

src/api/routes/login.ts, src/api/routes/render.ts, src/lib/TasksManager.ts, src/lib/browser/Page.ts, src/lib/browser/constants.ts, src/lib/helpers/errors.ts, src/lib/tasks/Render.ts, src/lib/tasks/Task.ts
1. **Improved Error Handling in Task Execution**:
- Changed how errors are caught and classified during task execution, particularly focusing on "Target page, context or browser has been closed" errors.
- These errors were previously causing container restarts because they were unhandled.
2. **Added Error Classification**:
- Added logic to classify certain errors as `'page_closed_too_soon'` when they match patterns in `RESPONSE_IGNORED_ERRORS`.
- This allows us to handle these errors gracefully instead of letting them crash the application.
3. **Fixed Redirection Handling**:
- Identified that our new error handling was incorrectly classifying JavaScript redirects as page closed errors.
- Added a check to first see if a redirection has occurred before classifying an error as …
=> fix: unhandled exceptions causing crash loops

src/lib/helpers/validateURL.ts
sometimes invalid urls are able to pass through, this should stop them and mark them as blocked.
```
TypeError [ERR_INVALID_URL]: Invalid URL
at new NodeError (node:internal/errors:405:5)
at new URL (node:internal/url:676:13)
at Page.<anonymous> (/app/renderscript/dist/lib/browser/Page.js:310:28)
at Page._callHandler (/app/renderscript/node_modules/playwright-core/lib/client/eventEmitter.js:71:29)
at Page.emit (/app/renderscript/node_modules/playwright-core/lib/client/eventEmitter.js:66:42)
at BrowserContext._onRequest (/app/renderscript/node_modules/playwright-core/lib/client/browserContext.js:181:20)
at Proxy.<anonymous> (/app/renderscript/node_modules/playwright-core/lib/client/browserContext.js:151:16)
at Proxy._callHandler (/app/renderscript/node_modules/playwright-core/lib/client/eve …
```
=> fix: invalid url catch
